### ISSUE TITLE
列表点击后有闪动现象

### ISSUE THREAD

**Issue by lu769257351** [dueeeke/dkplayer#14]
你好，我在列表点击播放的时候发现播放前都会有黑屏闪一下的情况，我怀疑是不视频的宽高比例和封面的宽高比例不一致的原因造成。

**Comment by dueeeke** [comment]
@lu769257351 你使用的是最新版吗，最新版不会播放前黑屏闪一下

**Comment by lu769257351** [comment]
你好，新版沒有問題了，但是點擊播放時，播放框變小的現象還有。

**Comment by dueeeke** [comment]
@lu769257351 这不是播放框缩小，这是缩略图和视频大小不一致

**Comment by lu769257351** [comment]
好的，谢谢，我后面再观察看看。发自我的华为手机-------- 原始邮件 --------主题：Re: [dueeeke/dkplayer] 列表点击后有闪动现象 (#14)发件人：dueeeke 收件人：dueeeke/dkplayer 抄送：lu769257351 ,Mention @lu769257351 这不是播放框缩小，这是缩略图和视频大小不一致

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dueeeke/dkplayer","title":"dueeeke/dkplayer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dueeeke/dkplayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dueeeke in #14: @lu769257351 这不是播放框缩小，这是缩略图和视频大小不一致"}],"action":{"name":"View Issue","url":"https://github.com/dueeeke/dkplayer/issues/14#issuecomment-381965598"}}}

**Comment by lu769257351** [comment]
谢谢，请问这个支持列表在滚蛋后从新后方之前播放的视频不是从头开始，而是接着上次播放的地方再开始功能？

**Comment by lu769257351** [comment]
我有看到skipPositionWhenPlay这个方法，但是设置了没效果
