### ISSUE TITLE
竖屏显示时无法强制全屏播放

### ISSUE THREAD

**Issue by chat491231702** [dueeeke/dkplayer#17]
比如要播放的视频是9:16的 分辨率是 1080*1920 ，希望在竖屏状态时可以铺满全屏，现在小米mix2手机上或其他的18:9的全面屏手机，SCREEN_SCALE_DEFAULT 设置为这个播放的时候，上下会留有黑色边距，没有铺满全屏，希望可以像抖音那样，强制铺满全屏，但是画面又不拉伸。已验证抖音的视频都是9:16的，且在小米mix2手机上抖音播放时上下不会有黑色边距。

**Comment by dueeeke** [comment]
最新版增加“居中裁剪”，已解决你说的问题，不清楚可参照demo

**Comment by dueeeke** [comment]
最新版已解决你说的问题，具体参考demo
