### ISSUE TITLE
继续播放问题

### ISSUE THREAD

**Issue by lu769257351** [dueeeke/dkplayer#18]
你好，请问这支持继续播放吗？我指的是在列表里播放一条后，然后滚动列表，当前播放滚出屏幕列表后就停止了，当再次滚回来时再次播放能不能接着上次播放的地方接着播放。

**Comment by dueeeke** [comment]
@lu769257351 功能已添加，请切到dev分支查看

**Comment by lu769257351** [comment]
好的，辛苦了发自我的华为手机-------- 原始邮件 --------主题：Re: [dueeeke/dkplayer] 继续播放问题 (#18)发件人：dueeeke 收件人：dueeeke/dkplayer 抄送：lu769257351 ,Mention @lu769257351 功能已添加，请切到dev分支查看

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dueeeke/dkplayer","title":"dueeeke/dkplayer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dueeeke/dkplayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dueeeke in #18: @lu769257351 功能已添加，请切到dev分支查看"}],"action":{"name":"View Issue","url":"https://github.com/dueeeke/dkplayer/issues/18#issuecomment-382637249"}}}

**Comment by Tomsyb** [comment]
我如果切换到MediaPlayer继续播放无法播放，但是切换到其他两个播放核心是可以实现继续播放的

**Comment by Tomsyb** [comment]
我如果切换到MediaPlayer重新播放一直在转圈圈，但是切换到其他两个播放核心是可以实现重新播放的
