### ISSUE TITLE
如何播放时自动全屏

### ISSUE THREAD

**Issue by marscl** [dueeeke/dkplayer#183]
如何播放时自动全屏

**Comment by dueeeke** [comment]
你是说直接全屏播放吗

**Comment by marscl** [comment]
是的

**Comment by dueeeke** [comment]
有相关demo

**Comment by marscl** [comment]
好的 那在fragment中使用player生命周期怎么管理呢

**Comment by dueeeke** [comment]
和activity一样

**Comment by marscl** [comment]
@Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        String url=getArguments().getString("url");
        String title=getArguments().getString("title");
        controller = new FullScreenController(mContext);
        player.setPlayerConfig(new PlayerConfig.Builder().autoRotate()
                .setCustomMediaPlayer(new ExoMediaPlayer(mContext))
                .build());
        player.setUrl(url);
        player.setTitle(title);
        player.setVideoController(controller);
        player.setScreenScale(IjkVideoView.SCREEN_SCALE_16_9);
        player.start();
    }

    @Override
    public void onPause() {
        Log.e("TAG","pause");
        super.onPause();
        player.pause();
    }

    @Override
    public void onResume() {
        Log.e("TAG","resume");
        super.onResume();
        player.resume();
    }

    @Override
    public void onDestroy() {
        Log.e("TAG","destory");
        super.onDestroy();
        player.release();
    }
这样按back无法退出

**Comment by dueeeke** [comment]
做一下桥接，在fragment中定义一个onbackpress,然后再相应的activity中调用此方法
