### ISSUE TITLE
多次设置标题好像只有第一次生效

### ISSUE THREAD

**Issue by marscl** [dueeeke/dkplayer#191]
多次设置标题好像只有第一次生效

**Comment by dueeeke** [comment]
是的，我在controller做了判断，你可以去修改一下源码
下个版本我准备把设置标题挪到controller中，合理一点

**Comment by marscl** [comment]
exo播放本地m3u8时会白圈一直转，视频已经播放成功了

**Comment by mapeng1** [comment]
多次设置时请在设置前先release下
