### ISSUE TITLE
请问下，可以设置关闭流量播放提醒吗？

### ISSUE THREAD

**Issue by gh-txgdr** [dueeeke/dkplayer#204]

**Comment by dueeeke** [comment]
把IjkVideoView中的IS_PLAY_ON_MOBILE_NETWORK赋值成true就行，它是public的

**Comment by gh-txgdr** [comment]
这个是2.5.4版本加进去的吗

**Comment by dueeeke** [comment]
原来在PlayerConstants 这个类里面，2.5.4移到IjkVideoView中了，并且把PlayerConstants 删除了

**Comment by gh-txgdr** [comment]
PlayerConstants 这个要设置IjkVideoView还是PlayerConfig，怎么设置的

**Comment by dueeeke** [comment]
2.5.7版加了setPlayOnMobileNetwork方法，可直接设置
