### ISSUE TITLE
提示：出了点小问题，请稍后再试

### ISSUE THREAD

**Issue by wangxp423** [dueeeke/dkplayer#21]
我在运行demo的时候 大部分都提示这个，视频基本都不能播放，难道是我网络问题、？我想问下博主有没有能看的直播源，我想试下rtmp的直播源是否可以播放。

**Comment by dueeeke** [comment]
@wangxp423 log发一下

**Comment by wangxp423** [comment]
04-20 12:55:43.286 25923-25923/com.dueeeke.dkplayer V/IJKMEDIA: setDataSource: path http://mov.bn.netease.com/open-movie/nos/flv/2017/01/03/SC8U8K7BC_hd.flv
04-20 12:55:43.286 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://mov.bn.netease.com/open-movie/nos/flv/2017/01/03/SC8U8K7BC_hd.flv")
    ijkmp_set_data_source(url="http://mov.bn.netease.com/open-movie/nos/flv/2017/01/03/SC8U8K7BC_hd.flv")=0
    IjkMediaPlayer_prepareAsync
04-20 12:55:43.287 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: ijkmp_prepare_async()
04-20 12:55:43.287 25923-25923/com.dueeeke.dkplayer I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
04-20 12:55:43.287 25923-6654/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6654] ff_msg_loop
04-20 12:55:43.287 25923-25923/com.dueeeke.dkplayer I/IJKMEDIA: libavutil    : 55.78.100
04-20 12:55:43.287 25923-6654/com.dueeeke.dkplayer D/IJKMEDIA: message_loop
04-20 12:55:43.287 25923-25923/com.dueeeke.dkplayer I/IJKMEDIA: libavcodec   : 57.107.100
    libavformat  : 57.83.100
    libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    player-opts : loop                         = 1
    player-opts : enable-accurate-seek         = 1
    player-opts : mediacodec                   = 0
    player-opts : mediacodec-auto-rotate       = 0
    player-opts : mediacodec-handle-resolution-change = 0
    format-opts : ijkapplication               = -1418214608
    format-opts : ijkiomanager                 = -1416695952
    ===================
04-20 12:55:43.288 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: ijkmp_prepare_async()=0
04-20 12:55:43.288 25923-25923/com.dueeeke.dkplayer E/DKPlayer: STATE_PREPARING
    PLAYER_NORMAL
04-20 12:55:43.289 25923-6654/com.dueeeke.dkplayer D/IJKMEDIA: FFP_MSG_FLUSH:
04-20 12:55:43.289 25923-6656/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6656] ff_read
04-20 12:55:43.290 25923-6656/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
04-20 12:55:43.291 25923-6655/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6655] ff_vout
04-20 12:55:43.291 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
    ijkmp_set_android_surface(surface=0xffd2ddb0)
    ffpipeline_set_surface()
    ijkmp_set_android_surface(surface=0xffd2ddb0)=void
04-20 12:55:43.293 25923-6656/com.dueeeke.dkplayer I/IJKMEDIA: Hit DNS cache hostname = mov.bn.netease.com
04-20 12:55:43.298 20018-20043/? I/XiaomiFirewall: firewall pkgName:com.dueeeke.dkplayer, result:0x0
04-20 12:55:43.302 25923-6656/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
04-20 12:55:43.448 25923-6656/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
04-20 12:55:43.548 25923-6656/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
04-20 12:55:43.548 25923-6656/com.dueeeke.dkplayer E/IJKMEDIA: http://mov.bn.netease.com/open-movie/nos/flv/2017/01/03/SC8U8K7BC_hd.flv: Connection reset by peer
04-20 12:55:43.548 25923-6656/com.dueeeke.dkplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6656]
04-20 12:55:43.549 25923-6654/com.dueeeke.dkplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
04-20 12:55:43.549 25923-25923/com.dueeeke.dkplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
04-20 12:55:43.549 25923-25923/com.dueeeke.dkplayer E/DKPlayer: STATE_ERROR

这是哪个VOD的，重试

**Comment by wangxp423** [comment]
04-20 12:56:52.971 25923-25923/com.dueeeke.dkplayer V/IJKMEDIA: setDataSource: path rtmp://live.hkstv.hk.lxdns.com/live/hks
04-20 12:56:52.971 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")
    ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")=0
    IjkMediaPlayer_prepareAsync
    ijkmp_prepare_async()
04-20 12:56:52.972 25923-25923/com.dueeeke.dkplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
04-20 12:56:52.972 25923-25923/com.dueeeke.dkplayer I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
    libavutil    : 55.78.100
04-20 12:56:52.972 25923-25923/com.dueeeke.dkplayer I/IJKMEDIA: libavcodec   : 57.107.100
    libavformat  : 57.83.100
    libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    player-opts : loop                         = 1
    player-opts : enable-accurate-seek         = 1
    player-opts : mediacodec                   = 0
    player-opts : mediacodec-auto-rotate       = 0
    player-opts : mediacodec-handle-resolution-change = 0
    format-opts : ijkapplication               = -1416219936
    format-opts : ijkiomanager                 = -1416695952
    ===================
04-20 12:56:52.972 25923-6877/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6877] ff_msg_loop
04-20 12:56:52.972 25923-6877/com.dueeeke.dkplayer D/IJKMEDIA: message_loop
04-20 12:56:52.973 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: ijkmp_prepare_async()=0
04-20 12:56:52.973 25923-25923/com.dueeeke.dkplayer E/DKPlayer: STATE_PREPARING
    PLAYER_NORMAL
04-20 12:56:52.973 25923-6879/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6879] ff_read
04-20 12:56:52.974 25923-6879/com.dueeeke.dkplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
04-20 12:56:52.973 25923-6878/com.dueeeke.dkplayer I/IJKMEDIA: SDL_RunThread: [6878] ff_vout
04-20 12:56:52.977 25923-6877/com.dueeeke.dkplayer D/IJKMEDIA: FFP_MSG_FLUSH:
04-20 12:56:52.979 25923-6879/com.dueeeke.dkplayer I/IJKMEDIA: Hit DNS cache hostname = live.hkstv.hk.lxdns.com
04-20 12:56:52.980 25923-25923/com.dueeeke.dkplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
    ijkmp_set_android_surface(surface=0xffd2ddb0)
    ffpipeline_set_surface()
    ijkmp_set_android_surface(surface=0xffd2ddb0)=void
04-20 12:56:52.981 20018-20043/? I/XiaomiFirewall: firewall pkgName:com.dueeeke.dkplayer, result:0x0
04-20 12:56:52.983 25923-6879/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
04-20 12:56:53.138 25923-6879/com.dueeeke.dkplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
04-20 12:56:53.238 25923-6879/com.dueeeke.dkplayer E/IJKMEDIA: Cannot read RTMP handshake response
    rtmp://live.hkstv.hk.lxdns.com/live/hks: Connection reset by peer
04-20 12:56:53.238 25923-6879/com.dueeeke.dkplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6879]
04-20 12:56:53.238 25923-6877/com.dueeeke.dkplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
04-20 12:56:53.239 25923-25923/com.dueeeke.dkplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
04-20 12:56:53.239 25923-25923/com.dueeeke.dkplayer E/DKPlayer: STATE_ERROR


这是哪个LIVE 中hks这连接不行，我在网上看到好多说这个可以的，但是我这都不行 不知道是不是公司网络问题。

**Comment by dueeeke** [comment]
@wangxp423 应该是你那边网有问题，检查一下是否设置代理
