### ISSUE TITLE
Android4.4 在最新版本上播放出错

### ISSUE THREAD

**Issue by suzhonxia** [dueeeke/dkplayer#210]
Android 4.4在dkplayer 2.5.6上播放视频crash。
IjkVideoView 的addDisplay 函数逻辑有问题：如果是4.4的手机，一定会初始化surfaceView，然后再onVideoSizeChanged 回调中就会crash（mUsingSurfaceView 为false，mTextureView 为null）

**Comment by suzhonxia** [comment]
![1](https://user-images.githubusercontent.com/16772107/55377746-f9e43680-5548-11e9-9111-18394ad74b43.png)
![2](https://user-images.githubusercontent.com/16772107/55377750-fc469080-5548-11e9-9158-65da80665a2d.png)

**Comment by dueeeke** [comment]
已经在2.5.7修复了
