### ISSUE TITLE
如何暂停后继续播放的问题

### ISSUE THREAD

**Issue by booldplx** [dueeeke/dkplayer#219]
一个RecyclerView里面,假如先播第一条,没有播放完我点击第二条播放了,然后我又点第一条播放,怎样设置第一条视频是继续上次播放的,而不是每次都从头开始播放

**Comment by dueeeke** [comment]
public void setProgressManager(@Nullable ProgressManager progressManager)可以实现，demo中有提供演示，ProgressManager 是一个抽象类，demo是使用静态的hashmap实现的，可以达到退出页面也保存进度的功能，如不需要你可以使用非静态hashmap实现，如果需退出app也能保存进度，可自行使用sharedpreference，数据库等持久化数据方式实现

**Comment by booldplx** [comment]
看到了  谢谢
