### ISSUE TITLE
列表悬浮播放没法全屏播放吗？

### ISSUE THREAD

**Issue by lu769257351** [dueeeke/dkplayer#25]
列表悬浮播放没法全屏播放吗？

**Comment by dueeeke** [comment]
视频全屏需要依赖activity，而悬浮窗的时候播放器已经不属于某个具体的activity了，故不能全屏

**Comment by lu769257351** [comment]
好的，了解了，发自我的华为手机-------- 原始邮件 --------主题：Re: [dueeeke/dkplayer] 列表悬浮播放没法全屏播放吗？ (#25)发件人：dueeeke 收件人：dueeeke/dkplayer 抄送：lu769257351 ,State change 视频全屏需要依赖activity，而悬浮窗的时候播放器已经不属于某个具体的activity了，故不能全屏

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dueeeke/dkplayer","title":"dueeeke/dkplayer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dueeeke/dkplayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dueeeke in #25: 视频全屏需要依赖activity，而悬浮窗的时候播放器已经不属于某个具体的activity了，故不能全屏"}],"action":{"name":"View Issue","url":"https://github.com/dueeeke/dkplayer/issues/25#issuecomment-384169716"}}}
