### ISSUE TITLE
保存播放进度问题

### ISSUE THREAD

**Issue by GFL0614** [dueeeke/dkplayer#268]
我设置保存播放进度之后 按返回键退出播放界面 保存进度没有问题  但是在播放界面直接划掉这个应用  保存播放进度就会失效  播放时会从上一次的保存的进度来开始播放   ijkVideoView.setProgressManager(new ProgressManagerImpl());   这个代码写在.start();之前

**Comment by dueeeke** [comment]
我是使用hashmap实现的，你可以使用持久化方式实现

**Comment by GFL0614** [comment]
> 我是使用HashMap中实现的，你可以使用持久化方式实现

我已经持久化实现了  按返回键退出播放界面   再关闭软件正常保存  但是在播放界面 直接划掉应用 进度就没有保存到数据库

**Comment by dueeeke** [comment]
继承VideoView重写onSaveInstanceState方法，在此方法内再保存一下进度

**Comment by dueeeke** [comment]
3.0.1已经解决
