### ISSUE TITLE
3.0 严重bug ,列表模式用数据流量必现ANR,而用wifi不会，应该是checkNetwork部分代码有问题

### ISSUE THREAD

**Issue by kyriej** [dueeeke/dkplayer#272]

**Comment by kyriej** [comment]
经查阅发现videoViewManager类中

  public void release() {
        for (int i = 0; i < mVideoViews.size(); i++) {
            Log.e("videomanager->",""+i);
            VideoView vv = mVideoViews.get(i);
            if (vv != null) {
                vv.release();
                i--;
            }
        }
    }

其中i--是导致ANR的原因，注释掉即可

**Comment by dueeeke** [comment]
3.0.1已经解决
