### ISSUE TITLE
列表播放进入竖屏全屏，然后点击全屏按钮切换横竖屏怎么实现

### ISSUE THREAD

**Issue by KafukaChen** [dueeeke/dkplayer#28]
需求是这样的，列表播放情况下，没有全屏键，点击视频进入竖着的全屏，全屏状态下有全屏按键，点击全屏键是在全屏状态下横竖屏切换，类似微博播放视频，demo里没看到这种效果，求指点怎么实现

**Comment by dueeeke** [comment]
不是很明白。点击视频是跳转到新页面吗，你说的微博就是跳转新页面，新页面是一个列表

**Comment by KafukaChen** [comment]
嗯了解，微博的确很多视频播放时挑衅页面列表。这样博主，你搜索 “科技美学” 的置顶微博，那条视频的播放场景，你看看

**Comment by dueeeke** [comment]
已经实现，请到demo的“EXTEND”里面查看，代码不是很完美，需要你自己优化一下

**Comment by KafukaChen** [comment]
我把一样的代码放到列表播放的适配器中   整个列表都横过来了，也不全屏播放了
public class VideoRecyclerViewAdapter extends RecyclerView.Adapter<VideoRecyclerViewAdapter.VideoHolder> {

    private static final String TAG = "VideoRecyclerViewAdapte";
        private List<VideoBean> videos;
        private Context context;

        public VideoRecyclerViewAdapter(List<VideoBean> videos, Context context) {
            this.videos = videos;
            this.context = context;
        }

        @Override
        public VideoHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View itemView = LayoutInflater.from(context).inflate(R.layout.item_video_auto_play, parent, false);
            return new VideoHolder(itemView);

        }

        @Override
        public void onBindViewHolder(final VideoHolder holder, int position) {

            VideoBean videoBean = videos.get(position);
            Glide.with(context)
                    .load(videoBean.getThumb())
                    .crossFade()
                    .placeholder(android.R.color.darker_gray)
                    .into(holder.mController.getThumb());


//            holder.ijkVideoView.setPlayerConfig(holder.mPlayerConfig);
            holder.ijkVideoView.setUrl(videoBean.getUrl());
            holder.ijkVideoView.setTitle(videoBean.getTitle());
            holder.ijkVideoView.setVideoController(holder.mController);
            holder.title.setText(videoBean.getTitle());

            holder.ijkVideoView.setOnClickListener(v -> {
                Log.d(TAG, "onBindViewHolder: onClick");
                holder.ijkVideoView.startFullScreen();
                holder.mController.setPlayState(holder.ijkVideoView.getCurrentPlayState());
                holder.mController.setPlayerState(holder.ijkVideoView.getCurrentPlayerState());
            });
//            holder.ijkVideoView.setTag(position);
        }

        @Override
        public int getItemCount() {
            return videos.size();
        }

        public class VideoHolder extends RecyclerView.ViewHolder {

            private RotateIjkVideoView ijkVideoView;
//            private StandardVideoController controller;
            private TextController mController;
            private TextView title;
            private PlayerConfig mPlayerConfig;

            VideoHolder(View itemView) {
                super(itemView);
                ijkVideoView = itemView.findViewById(R.id.video_player);
                int widthPixels = context.getResources().getDisplayMetrics().widthPixels;
                ijkVideoView.setLayoutParams(new LinearLayout.LayoutParams(widthPixels, widthPixels * 9 / 16 + 1));
                mController = new TextController(context);
                title = itemView.findViewById(R.id.tv_title);
                mPlayerConfig = new PlayerConfig.Builder()
                        .enableCache()
                        .autoRotate()
                        .addToPlayerManager()//required
//                        .usingAndroidMediaPlayer()
//                        .savingProgress()
                        .build();
            }
        }
    }

**Comment by KafukaChen** [comment]
博主能出一个列表中这样逻辑的例子么

**Comment by dueeeke** [comment]
已实现

**Comment by KafukaChen** [comment]
非常感谢，但是为啥设置不了封面，我把你设置封面的代码打开，依旧没有效果

**Comment by dueeeke** [comment]
`public class RotateIjkVideoView extends IjkVideoView{
    public RotateIjkVideoView(@NonNull Context context) {
        super(context);
    }

    public RotateIjkVideoView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public RotateIjkVideoView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }


    @Override
    public void startFullScreen() {
        setVideoController(mVideoController);
        Activity activity = WindowUtil.scanForActivity(getContext());
        if (activity == null) return;
        if (isFullScreen) return;
        WindowUtil.hideSystemBar(getContext());
        this.removeView(playerContainer);
        ViewGroup contentView = activity
                .findViewById(android.R.id.content);
        LayoutParams params = new LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        contentView.addView(playerContainer, params);
        isFullScreen = true;
        setPlayerState(PLAYER_FULL_SCREEN);
    }

    @Override
    public void stopFullScreen() {
        setVideoController(null);
        Activity activity = WindowUtil.scanForActivity(getContext());
        if (activity == null) return;
        if (!isFullScreen) return;
        WindowUtil.showSystemBar(getContext());
        ViewGroup contentView = activity
                .findViewById(android.R.id.content);
        contentView.removeView(playerContainer);
        LayoutParams params = new LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        this.addView(playerContainer, params);
        isFullScreen = false;
        setPlayerState(PLAYER_NORMAL);
    }

    @Override
    public void setVideoController(@Nullable BaseVideoController mediaController) {
        playerContainer.removeView(mVideoController);
        if (mediaController != null) {
            mediaController.setMediaPlayer(this);
            LayoutParams params = new LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT);
            playerContainer.addView(mediaController, params);
            mVideoController = mediaController;
        }
    }

    @Override
    public void onPrepared() {
        super.onPrepared();
        //暂时移除Controller
        setVideoController(null);
    }

    @Override
    public void release() {
        setVideoController(mVideoController);
        super.release();
    }

    @Override
    public void stopPlayback() {
        setVideoController(mVideoController);
        super.stopPlayback();
    }
}`

`public class RotateRecyclerViewAdapter extends RecyclerView.Adapter<RotateRecyclerViewAdapter.VideoHolder> {

        private List<VideoBean> videos;
        private Context context;

        public RotateRecyclerViewAdapter(List<VideoBean> videos, Context context) {
            this.videos = videos;
            this.context = context;
        }

        @Override
        public VideoHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View itemView = LayoutInflater.from(context).inflate(R.layout.item_video_rotate, parent, false);
            return new VideoHolder(itemView);

        }

        @Override
        public void onBindViewHolder(final VideoHolder holder, int position) {

            VideoBean videoBean = videos.get(position);
            Glide.with(context)
                    .load(videoBean.getThumb())
                    .crossFade()
                    .placeholder(android.R.color.darker_gray)
                    .into(holder.controller.getThumb());
            holder.ijkVideoView.setPlayerConfig(holder.mPlayerConfig);
            holder.ijkVideoView.setUrl(videoBean.getUrl());
            holder.ijkVideoView.setTitle(videoBean.getTitle());
            holder.ijkVideoView.setVideoController(holder.controller);
            holder.title.setText(videoBean.getTitle());
            holder.ijkVideoView.setOnClickListener(v -> {
                holder.ijkVideoView.startFullScreen();
                holder.ijkVideoView.start();
                //需在setVideoController之后调用
                holder.controller.setPlayerState(holder.ijkVideoView.getCurrentPlayerState());
                holder.controller.setPlayState(holder.ijkVideoView.getCurrentPlayState());
            });
//            holder.ijkVideoView.setTag(position);
        }

        @Override
        public int getItemCount() {
            return videos.size();
        }

        public class VideoHolder extends RecyclerView.ViewHolder {

            private IjkVideoView ijkVideoView;
            private RotateInFullscreenController controller;
            private TextView title;
            private PlayerConfig mPlayerConfig;

            VideoHolder(View itemView) {
                super(itemView);
                ijkVideoView = itemView.findViewById(R.id.video_player);
                int widthPixels = context.getResources().getDisplayMetrics().widthPixels;
                ijkVideoView.setLayoutParams(new LinearLayout.LayoutParams(widthPixels, widthPixels * 9 / 16 + 1));
                controller = new RotateInFullscreenController(context);
                title = itemView.findViewById(R.id.tv_title);
                mPlayerConfig = new PlayerConfig.Builder()
//                        .enableCache()
//                        .autoRotate()//不能开启自动旋转
                        .addToPlayerManager()//required
//                        .usingAndroidMediaPlayer()
//                        .savingProgress()
                        .build();
            }
        }
    }`

**Comment by dueeeke** [comment]
`public class RotateRecyclerViewAdapter extends RecyclerView.Adapter<RotateRecyclerViewAdapter.VideoHolder> {

    private List<VideoBean> videos;
    private Context context;

    public RotateRecyclerViewAdapter(List<VideoBean> videos, Context context) {
        this.videos = videos;
        this.context = context;
    }

    @Override
    public VideoHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(context).inflate(R.layout.item_video_rotate, parent, false);
        return new VideoHolder(itemView);

    }

    @Override
    public void onBindViewHolder(final VideoHolder holder, int position) {

        VideoBean videoBean = videos.get(position);
        Glide.with(context)
                .load(videoBean.getThumb())
                .crossFade()
                .placeholder(android.R.color.darker_gray)
                .into(holder.controller.getThumb());
        holder.ijkVideoView.setPlayerConfig(holder.mPlayerConfig);
        holder.ijkVideoView.setUrl(videoBean.getUrl());
        holder.ijkVideoView.setTitle(videoBean.getTitle());
        holder.ijkVideoView.setVideoController(holder.controller);
        holder.title.setText(videoBean.getTitle());
    }

    @Override
    public int getItemCount() {
        return videos.size();
    }

    public class VideoHolder extends RecyclerView.ViewHolder {

        private IjkVideoView ijkVideoView;
        private RotateInFullscreenController controller;
        private TextView title;
        private PlayerConfig mPlayerConfig;

        VideoHolder(View itemView) {
            super(itemView);
            ijkVideoView = itemView.findViewById(R.id.video_player);
            int widthPixels = context.getResources().getDisplayMetrics().widthPixels;
            ijkVideoView.setLayoutParams(new LinearLayout.LayoutParams(widthPixels, widthPixels * 9 / 16 + 1));
            controller = new RotateInFullscreenController(context);
            title = itemView.findViewById(R.id.tv_title);
            mPlayerConfig = new PlayerConfig.Builder()
//                        .enableCache()
//                        .autoRotate()//不能开启自动旋转
                    .addToPlayerManager()//required
//                        .usingAndroidMediaPlayer()
//                        .savingProgress()
                    .build();
        }
    }
}`

`public class RotateIjkVideoView extends IjkVideoView {
    public RotateIjkVideoView(@NonNull Context context) {
        super(context);
    }

    public RotateIjkVideoView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public RotateIjkVideoView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public void startFullScreen() {
        setOnClickListener(null);
        setVideoController(mVideoController);
        Activity activity = WindowUtil.scanForActivity(getContext());
        if (activity == null) return;
        if (isFullScreen) return;
        WindowUtil.hideSystemBar(getContext());
        this.removeView(playerContainer);
        ViewGroup contentView = activity
                .findViewById(android.R.id.content);
        LayoutParams params = new LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        contentView.addView(playerContainer, params);
        isFullScreen = true;
        setPlayerState(PLAYER_FULL_SCREEN);
    }

    @Override
    public void stopFullScreen() {
        setVideoController(null);
        setOnClickListener(mOnClickListener);
        Activity activity = WindowUtil.scanForActivity(getContext());
        if (activity == null) return;
        if (!isFullScreen) return;
        WindowUtil.showSystemBar(getContext());
        ViewGroup contentView = activity
                .findViewById(android.R.id.content);
        contentView.removeView(playerContainer);
        LayoutParams params = new LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        this.addView(playerContainer, params);
        isFullScreen = false;
        setPlayerState(PLAYER_NORMAL);
    }

    @Override
    public void setVideoController(@Nullable BaseVideoController mediaController) {
        playerContainer.removeView(mVideoController);
        if (mediaController != null) {
            mediaController.setMediaPlayer(this);
            LayoutParams params = new LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT);
            playerContainer.addView(mediaController, params);
            mVideoController = mediaController;
        }
    }

    @Override
    public void onPrepared() {
        super.onPrepared();
        if (isFullScreen) return;
        //暂时移除Controller
        setVideoController(null);
        setOnClickListener(mOnClickListener);
    }

    private OnClickListener mOnClickListener = new OnClickListener() {
        @Override
        public void onClick(View v) {
            start();
            startFullScreen();
        }
    };

    @Override
    public void release() {
        setVideoController(mVideoController);
        super.release();
    }

    @Override
    public void stopPlayback() {
        setVideoController(mVideoController);
        super.stopPlayback();
    }
}`

这是最终版，看看符不符合你的需求

**Comment by dueeeke** [comment]
public class RotateInFullscreenController extends StandardVideoController {

    private boolean isLandscape;

    public RotateInFullscreenController(@NonNull Context context) {
        super(context);
    }

    public RotateInFullscreenController(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public RotateInFullscreenController(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }


    @Override
    protected void doStartStopFullScreen() {
        if (isLandscape) {
            WindowUtil.scanForActivity(getContext()).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
            isLandscape = false;
        } else {
            WindowUtil.scanForActivity(getContext()).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
            isLandscape = true;
        }
        fullScreenButton.setSelected(isLandscape);
    }

    @Override
    public void setPlayerState(int playerState) {
        super.setPlayerState(playerState);
        switch (playerState) {
            case IjkVideoView.PLAYER_FULL_SCREEN:
                fullScreenButton.setSelected(false);
                break;
        }

    }

    @Override
    public void onClick(View v) {

        int i = v.getId();
        if (i == R.id.fullscreen) {
            doStartStopFullScreen();
        } else if (i == R.id.lock) {
            doLockUnlock();
        } else if (i == R.id.iv_play || i == R.id.iv_replay) {
            doPauseResume();
        } else if (i == R.id.back) {
            if (isLandscape)
                WindowUtil.scanForActivity(getContext()).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
            mediaPlayer.stopFullScreen();
        } else if (i == R.id.thumb) {
            getThumb().setVisibility(GONE);
            mediaPlayer.start();
            mediaPlayer.startFullScreen();
        }
    }

    @Override
    public boolean onBackPressed() {
        if (isLocked) {
            show();
            Toast.makeText(getContext(), R.string.lock_tip, Toast.LENGTH_SHORT).show();
            return true;
        }
        if (mediaPlayer.isFullScreen()) {
            if (isLandscape)
                WindowUtil.scanForActivity(getContext()).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
            mediaPlayer.stopFullScreen();
            setPlayerState(IjkVideoView.PLAYER_NORMAL);
            return true;
        }
        return super.onBackPressed();
    }
}

controller也替换一下

**Comment by KafukaChen** [comment]
进入列表默认第一个播放，点击第一个进入全屏，点击视频会有加载样式，此时推出有问题；
进入列表，此时点击第二个视频，进入全屏播放，点击退出后此视频无法在进入全屏

**Comment by dueeeke** [comment]
已经改了，代码已上传，切到dev分支更新一下最新代码

**Comment by KafukaChen** [comment]
谢谢啊，真的感谢。今天研究了一天，依然有两个小问题，在此基础上，列表中视频播放时底部进度条消失了；我要在列表视频播放时增加一个常驻按键，比如音量键，一键开关，进全屏就消失（这个我会），但是做不了，不知道为啥，就是不能在列表视频中常驻，全屏常驻我没问题

**Comment by dueeeke** [comment]
已经实现，请切到dev分支，并同步最新代码

**Comment by KafukaChen** [comment]
导入项目后
mGestureDetector = new GestureDetector(getContext(), new GestureVideoController.MyGestureListener() {

这个 MyGestureListener 源码中是private的  报红。dev的demo中点进去是protected的
我是添加的依赖

**Comment by KafukaChen** [comment]
列表中视频播放完成后点击封面或者重新播放按钮无法再次进入全屏播放，播放完一次就不行了

**Comment by dueeeke** [comment]
https://github.com/dueeeke/dkplayer/blob/dev/app/src/main/java/com/dueeeke/dkplayer/widget/controller/RotateInFullscreenController.java#L91
把85行的id == R.id.iv_replay移到91行即可
