### ISSUE TITLE
全屏播放画幅出问题

### ISSUE THREAD

**Issue by KafukaChen** [dueeeke/dkplayer#34]
老哥是不是最近改了哪里啊，画幅突然出问题了，用手机全屏拍摄未裁剪拍的视频播放出来突然就变小了,我在setPlayerState 的 case IjkVideoView.PLAYER_FULL_SCREEN: 中设置画幅setScreenScale也不起作用了，如图所示
![_20180515155230](https://user-images.githubusercontent.com/22462950/40043810-292b1916-5858-11e8-9b39-ca91ed644e6e.jpg)

**Comment by dueeeke** [comment]
你用的最新版吗？

**Comment by KafukaChen** [comment]
用的下面这种依赖方式
    //dkplayer
    //required, enough for most devices.
    compile 'com.github.dueeeke.dkplayer:dkplayer-java:2.4.0'
    compile 'com.github.dueeeke.dkplayer:dkplayer-armv7a:2.4.0'
//    Other ABIs: optional
    compile 'com.github.dueeeke.dkplayer:dkplayer-armv5:2.4.0'
    compile 'com.github.dueeeke.dkplayer:dkplayer-arm64:2.4.0'
    compile 'com.github.dueeeke.dkplayer:dkplayer-x86:2.4.0'
    compile 'com.github.dueeeke.dkplayer:dkplayer-x86_64:2.4.0'

我刚才将 RotateInFullscreenActivity 中的url换成了本地视频  全屏模式下播放也存在问题，应该不是我其他代码的问题，老哥你可以将其中url换成本地视频试试

**Comment by dueeeke** [comment]
播放本地视频要开启硬解

**Comment by KafukaChen** [comment]
播放网络视频是否可以开启硬解码，是否会有问题。我要将本地视频上传到服务端，但是本地视频播放盒网络视频播放都需要，发现无论本地视频还是已经上传成功的网络视频播放画幅都缩小了，所以有前面问题的担忧

**Comment by KafukaChen** [comment]
新发现播放横向视频不会有问题，播放竖向拍摄的视频缩小了

**Comment by dueeeke** [comment]
用手机录制的视频一般会包含一个旋转信息，开启硬解码ijkplayer会自动处理该旋转信息，我在软解的时候没有去处理，处理方式也很简单，就是再视频旋转90度或270度的时候交换一下视频的宽高，[https://github.com/dueeeke/dkplayer/blob/dev/dkplayer-java/src/main/java/com/dueeeke/videoplayer/widget/ResizeTextureView.java#L44](url)

**Comment by KafukaChen** [comment]
不是很懂。。。而且我导的依赖 ResizeTextureView  该类中宽高并未交换

**Comment by dueeeke** [comment]
要发布新版本
