### ISSUE TITLE
推送视频被暂停

### ISSUE THREAD

**Issue by lu769257351** [dueeeke/dkplayer#36]
当视频在播放时，收到推送消息时，视频被暂停，但是推送结束后无法自动继续播放，需要点击播放

**Comment by dueeeke** [comment]
你说的这两个问题应该都是因为系统的音频焦点发生了改变，因为我在播放器内监听了系统的音频焦点，如果发现系统中有其他播放器（比如你的音乐播放器）获得了音频焦点，播放器将暂停播放，就是为了避免同时播放视频和音乐，如果你不在乎这个，你大可去掉这个监听，应该就能解决你说的问题

**Comment by lu769257351** [comment]
好的，谢谢你
