### ISSUE TITLE
Video stops playing before finishing

### ISSUE THREAD

**Issue by Serrust** [dueeeke/dkplayer#37]
Environment: Nexus 5, Android API 23
Description:
1. The user downloads the demo application and opens it
2. The user tries Auto Play Recycler View demo
3. Play any video.
4. There is high chance that the video stops somewhere before it finishes playing the entire video.
5. The view will go back to initial state (only show thumbnail and play button)

PS: You can use Mandarin to reply and I'd love to give  more specific description if you want (no Chinese input method installed on my laptop 2333).
my email address: wyz87100992@gmail.com

**Comment by Serrust** [comment]
I am testing using virtual device. I wonder if that is the problem of my testing device. I will keep updating.

**Comment by Serrust** [comment]
Using AVD Nexus 5X API 27, I cannot reproduce this issue. May I ask some possible reasons why nexus 5 api 23 is having this issue? Thanks.

**Comment by Serrust** [comment]
Using One Plus 5, API 27 also cannot reproduce this issue.

**Comment by dueeeke** [comment]
我觉得这应该是你模拟器的问题，我使用genymotion并未复现你说的问题，我使用Android p测试版，Android 8.0 Android7.1都未复现你说的问题

**Comment by Serrust** [comment]
谢谢dueeeke。
