### ISSUE TITLE
音量调节和亮度调节是不是反了

### ISSUE THREAD

**Issue by wlingf** [dueeeke/dkplayer#46]
用户应该是习惯了右边是音量调节，左边是亮度调节，而且主流的视频播放器都是这么设置，不知道作者反着是有何用意，还有就是能否开放接口，设置音量调节和亮度调节在左或是在右的这么一个功能，这样开发者就可以自由设置了
还有是否能开放更多的接口出来，例如：是否可以自由设置播放按钮，是否可以自定义进度条的颜色，或是提供获取对应view,让开发者自由设置

**Comment by dueeeke** [comment]
请阅读我的demo
