### ISSUE TITLE
不支持本地视频播放？？

### ISSUE THREAD

**Issue by toeii** [dueeeke/dkplayer#47]
试了下，SD卡下的视频文件播放不了，提示请重试

**Comment by dueeeke** [comment]
1.确定你有访问sd卡的权限，2 使用file协议

**Comment by toeii** [comment]
是的，同样的路径七牛上可以播放

**Comment by dueeeke** [comment]
什么格式和编码，还有日志提供一下

**Comment by toeii** [comment]
String path = "/storage/emulated/0/DCIM/Camera/VID_20180512_202414.mp4";
                File file = new File(path);
                if(file.exists()){
                    path = Uri.parse("file://"+file.getAbsolutePath()).toString();
                }
                dkVideo.setUrl(path);
                Logger.d("path====>"+path);

path====>file:////storage/emulated/0/DCIM/Camera/VID_20180512_202414.mp4

**Comment by toeii** [comment]
E/IJKMEDIA: http://127.0.0.1:57023/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FVID_20180512_202414.mp4: End of file
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by dueeeke** [comment]
不要打开缓存功能

**Comment by toeii** [comment]
👌 PlayerConfig.Builder去掉enableCache已经可以播放了

**Comment by sunshinecf** [comment]
看你们解说我居然成功了，感谢大神们默默奉献

**Comment by xiaoshizuzhang** [comment]
本地的m3u8文件可以播放吗？

**Comment by xiaoshizuzhang** [comment]
视频地址已拼接成完整地址，不是相对地址

**Comment by jiancheng2018** [comment]
怎么播放本地的视频呢？m3u8我试了可以

**Comment by yuxingfafu** [comment]
assets 目录下的应该要如何播放呀？

**Comment by a1042392710** [comment]
大佬，无法播放本地视频。PlayerConfig类已经移除了，我现在该如何才能播放本地视频

**Comment by ZakAnun** [comment]
> 大佬，无法播放本地视频。PlayerConfig类已经移除了，我现在该如何才能播放本地视频

通过对应的播放器去配置，比如 ExoPlayer，就通过 DataSource.Factory 去获取是否支持缓存的 DataSource

**Comment by OnrushingDrumstick** [comment]
为啥硬解码的api没有了

**Comment by SuperZhouyong** [comment]
![image](https://user-images.githubusercontent.com/20082068/125162625-887d9e80-e1bb-11eb-87bd-07ac8d37b3b6.png)
@Doikki 播放本地视频，重复点进去，回调有问题。 M3U8本地，Exo 播放

**Comment by liupeng176** [comment]
坑爹，刚选视频播放库的建议别选这个库，缓存都没有。每次播都从新下载。推荐的缓存方案更是坑爹，在安卓手机本地开了端口，启动服务。  所有的url都被重定向为明文流量 http://127.0.0.1:xxx/原视频url

**Comment by beginningjx** [comment]
播放本地加密的m3u8如果密匙为.key结尾的使用ijk内核会导致播放不了，会报
Filename extension of 'xxx.key' is not a common multimedia extension, blocked for security reasons.
这个错误，我的解决办法就是把密匙为.key结尾换成.m3u8结尾就可以播放了
