### ISSUE TITLE
关于recyclerview自动播放的逻辑

### ISSUE THREAD

**Issue by jerry120** [dueeeke/dkplayer#48]
你好!我在实现滑动自动播放的功能,然后在IjkVideoView上面添加了一个view用来显示当前视频的相关信息,想要的效果是视频播放的时候隐藏掉IjkVideoView上面那个view,视频停止播放就显示那个view,然后出现一个问题,就是有时候停止播放的那个IjkVideoView上面的view没有显示出来.我的逻辑是加在这里的
if (fl_video != null) {
                        Rect rect = new Rect();
                        fl_video.getLocalVisibleRect(rect);
                        int videoHeight = fl_video.getHeight();
                        if (rect.top == 0 && rect.bottom == videoHeight) {
                            ijkVideoView.start();
                            //todo
                            ll_info.setVisibility(View.INVISIBLE);
                            iv_image.setVisibility(View.INVISIBLE);
                            return;
                        }else {
                            ijkVideoView.stopPlayback();
                            ll_info.setVisibility(View.VISIBLE);
                            iv_image.setVisibility(View.VISIBLE);
                        }

                    }

或者加在这里
 recyclerView.setAdapter(adapter);
        recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {

            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                IjkVideoView ijkVideoView = (IjkVideoView) view.findViewById(R.id.video_player);
                RelativeLayout ll_info = (RelativeLayout) view.findViewById(R.id.ll_video_surfaceinfo);
                RoundedImageView iv_image = (RoundedImageView) view.findViewById(R.id.iv_image);
                if (ijkVideoView != null && !ijkVideoView.isFullScreen()) {
//                    Log.d("@@@@@@", "onChildViewDetachedFromWindow: called");
//                    int tag = (int) ijkVideoView.getTag();
//                    Log.d("@@@@@@", "onChildViewDetachedFromWindow: position: " + tag);
                    ijkVideoView.stopPlayback();
                    ll_info.setVisibility(View.VISIBLE);
                    iv_image.setVisibility(View.VISIBLE);

                }
            }
        });

但好像都没有解决这个问题,想请教一下.

**Comment by dueeeke** [comment]
这个最好加在controller上，或者监听播放和暂停的时间ijkVideoView.setVideoListener()
