### ISSUE TITLE
May I ask how to auto-replay the video?

### ISSUE THREAD

**Issue by yizhou-revyoo-me** [dueeeke/dkplayer#58]
I would like to start playing the same video once the video finishes playing. 
Is there anything like onCompleteListener or setOnPreparedListener in dkplayer? If there is, may I ask how to use it?
Thanks dueeeke.

**Comment by dueeeke** [comment]
PlayerConfig config = new PlayerConfig.Builder().setLooping().build();
        mIjkVideoView.setPlayerConfig(config);

**Comment by yizhou-revyoo-me** [comment]
Thanks dueeeke.
