### ISSUE TITLE
在recyclerView中使用surfaceview问题

### ISSUE THREAD

**Issue by fudaye** [dueeeke/dkplayer#59]
大神你好：

 我在RecyclerView中使用SurfaceView播放视频会有问题，在demo中黑屏有声音。在我自己的项目中，会导致视频画面永远是全屏的，不会根据窗口的大小该表，不知道什么原因，求指导，谢谢。

**Comment by dueeeke** [comment]
建议使用TextrueView来显示视频，还有不要打开硬解码，如果以上方法都不行，把视频地址给我，好定位问题

**Comment by fudaye** [comment]
http://test-video.tianchiapi.com/group3/M00/00/B1/CgEBJls_DtKAfbYHAACMZ6YqHC095.m3u8

这个视频地址能帮我看看什么问题吗，我用TextrueView显示的，没有开启硬解码，但是播放也正常，但是在暂停之后，继续播放的时候回从头播放，不知道是什么原因？求指导

**Comment by dueeeke** [comment]
我自己放到demo中测试是正常的
