### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by DevXue** [dueeeke/dkplayer#6]
我现在的项目，用的是Android原生的Mediaplayer来播放音乐的，  有个问题就是，首次打开播放一首音乐的时候，现在正在处于缓冲状态，  然而用户直接就拖动进度条到了中间，可是出现的效果就是 缓冲完了  又重新跑到了起点位置开始播放了，  我下载你的demo看了下，你用Mediaplayer来播放声音就没有出现这个情况，还有我发现我的onPrepared 方法和你的一毛一样，不知道为啥我就实现不了你的效果，你的demo中，我拖动到了中间，然后它就会在中间的位置开始缓冲， 缓冲好之后就在中间的位置开始播放了！   求大神给个思路   你这个是怎么实现的呢？

**Comment by dueeeke** [comment]
@DevXue 这是ijkplayer的默认行为，可能Mediaplayer并不支持这样，建议在音频没有加载出来的时候不要让用户seek进度
