### ISSUE TITLE
PlayerConfig中的setLooping在RecyclerView中不管用

### ISSUE THREAD

**Issue by Wilson-ch** [dueeeke/dkplayer#60]
大神你好

  我在你的RecyclerView demo里把PlayerConfig中加上了setLooping()，但是现在在RecyclerView中的视频并不会重播。
  现在我的RecyclerView中的视频都是m3u8格式的。请问有什么办法能让视频重播？

**Comment by dueeeke** [comment]
ijkplayer貌似不支持m3u8循环播放，不过我们可以自己实现循环逻辑，思路：监听播放完成事件，手动重新播放。只需在adapter中加入如下代码即可：
            holder.ijkVideoView.setVideoListener(new MyVideoListener() {
                @Override
                public void onComplete() {
                    super.onComplete();
                    holder.ijkVideoView.retry();
                }
            });

**Comment by Wilson-ch** [comment]
已经可以重播m3u8了！
感谢大神🙏！
