### ISSUE TITLE
怎么获取将要播放的视频大小

### ISSUE THREAD

**Issue by mutengc** [dueeeke/dkplayer#62]

**Comment by dueeeke** [comment]
继承IjkVideoView，重写onVideoSizeChanged(int videoWidth, int videoHeight)

**Comment by mutengc** [comment]
不好意思，我表述有点问题，是非wifi状态下播放视频需要花费多少流量

**Comment by dueeeke** [comment]
视频没播放之前是获取不到视频大小的，这要后台返回

**Comment by mutengc** [comment]
好的，谢谢了
