### ISSUE TITLE
The back arrow on API page, LIST page, EXTEND page, PIP pages are not working.

### ISSUE THREAD

**Issue by yizhou-revyoo-me** [dueeeke/dkplayer#65]
1. Click on API button,
2. Click back arrow on top bar. 
3. The user is not navigating back to the first page.

Environment: 
Samsung S8, Android 8.0.0

**Comment by dueeeke** [comment]
Add the following code

@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            finish();
        }
        return super.onOptionsItemSelected(item);
    }
