### ISSUE TITLE
报错End of file

### ISSUE THREAD

**Issue by qq570026938** [dueeeke/dkplayer#66]
第一次：https://m3.gaoqingmh.com/ppvod/Gb3lmnxi.m3u8  如果这个https开头的地址播放失败
，后面地址报错  End of file
http://m3.gaoqingmh.com/ppvod/cxTnMh9k.m3u8: End of file

**Comment by dueeeke** [comment]
地址失效了

**Comment by dueeeke** [comment]
#69

**Comment by qq570026938** [comment]
ok
