### ISSUE TITLE
关于视频播放器有时候不能播放的问题

### ISSUE THREAD

**Issue by pj567** [dueeeke/dkplayer#69]
打开demo直接依次播放http://jiajunhui.cn/video/kongchengji.mp4，https://mov.bn.netease.com/open-movie/nos/mp4/2016/06/22/SBP8G92E3_hd.mp4，http://jiajunhui.cn/video/edwin_rolling_in_the_deep.flv，http://jiajunhui.cn/video/allsharestar.mp4视频地址后  在用demo中的上面的api演示 、列表播放、扩展功能的视频就不能播放了，麻烦大神看看什么问题，是不是编译的库有问题

**Comment by dueeeke** [comment]
这是因为同一个域名即用了http又用了https,解决方法如下，重写ijkplayer中的setOptions方法
`IjkPlayer ijkPlayer = new IjkPlayer(this) {
                @Override
                public void setOptions() {
                    super.setOptions();
                    mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
                }
            };
            ijkVideoView.setPlayerConfig(new PlayerConfig.Builder().setCustomMediaPlayer(ijkPlayer).build());`
