### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by UglyFatOld** [dueeeke/dkplayer#7]
依赖项目运行时出现以下问题 菜鸟求助

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\bird\.gradle\caches\transforms-1\files-1.1\dkplayer-1.4.3.aar\f901af77260aac2fb095a0d389097849\jars\classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/dueeeke/videoplayer/player/IjkVideoView.class
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\bird\.gradle\caches\transforms-1\files-1.1\dkplayer-1.4.3.aar\f901af77260aac2fb095a0d389097849\jars\classes.jar

**Comment by dueeeke** [comment]
使用java8

**Comment by UglyFatOld** [comment]
![_20180122095830](https://user-images.githubusercontent.com/30892881/35202019-d2fcecbe-ff5a-11e7-8de7-1f525592dfb8.png)你好 感谢你的回复 我用的一直是java8啊
