### ISSUE TITLE
OPPO R9m 兼容问题

### ISSUE THREAD

**Issue by wang-qian** [dueeeke/dkplayer#72]
手机型号：OPPO R9m 
系统：android 5.1
问题描述：正常播放视频，然后点击手机左下角“多任务”按键视频暂停播放，在“多任务”列表里面重新点击进入播放的app，视频卡住不动，视频声音正常，拖动进度条视频画面也无法恢复正常。

**Comment by dueeeke** [comment]
你用的是TextrueView还是SurfaceView

**Comment by wang-qian** [comment]
使用默认的配置TextureView出现的情况。但是用SurfaceView也有问题，会进入IjkVideoView.STATE_ERROR 状态

**Comment by dueeeke** [comment]
视频地址给我一下

**Comment by wang-qian** [comment]
和视频源应该没关系，demo自带的视频源也会出现这种情况
http://mov.bn.netease.com/open-movie/nos/flv/2017/01/03/SC8U8K7BC_hd.flv
我使用的视频源
http://7xo22l.com1.z0.glb.clouddn.com/house/video/2018-07-13/S543536_2.mp4

**Comment by dueeeke** [comment]
有没有打开硬解

**Comment by wang-qian** [comment]
没有开启硬解码，和demo里面的PlayerActivity 配置一样，只是换了视频源

**Comment by dueeeke** [comment]
这应该是5.1系统的bug。我手上有一台5.1的手机也是这样，但我已经有了解决方法，继承ijkVideoview,重写addDisplay，如下。
    @Override
    protected void addDisplay() {
        super.addDisplay();
        if (mTextureView != null) {
            mTextureView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
                @Override
                public void onSurfaceTextureAvailable(SurfaceTexture surfaceTexture, int width, int height) {
                    mMediaPlayer.setSurface(new Surface(surfaceTexture));
                }

                @Override
                public void onSurfaceTextureSizeChanged(SurfaceTexture surfaceTexture, int width, int height) {

                }

                @Override
                public boolean onSurfaceTextureDestroyed(SurfaceTexture surfaceTexture) {
                    return false;
                }

                @Override
                public void onSurfaceTextureUpdated(SurfaceTexture surfaceTexture) {

                }
            });
        }
    }
当然你也可以直接该我library的源码。
这样做会导致另外一个问题，就是从后台切回来之后会黑屏一下，然后再显示画面。
还有另外一种方式就是在5.1系统使用surfaceview不会有此问题
