### ISSUE TITLE
视频链接403的话 打开会闪退

### ISSUE THREAD

**Issue by rtyheji** [dueeeke/dkplayer#73]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dueeeke.videoplayer.widget.StatusView.setMessage(java.lang.String)' on a null object reference
  at com.dueeeke.videoplayer.controller.BaseVideoController.setPlayState(BaseVideoController.java:87)

**Comment by dueeeke** [comment]
检查一下StatusView有没有初始化，就是继承BaseVideoController后重写initView要调父类initView，不然StatusView就会没有初始化，或者你重写setPlayState方法，不调用父类setPlayState，也可以避免空指针
