### ISSUE TITLE
在开始播放时preparing阶段总会出现topcontainer,bootomcontainer等控制栏，如何控制隐藏掉控制栏，我在setPlaysState里面preparing设置这些控制栏为gone，无效仍然显示，请教大佬如何改

### ISSUE THREAD

**Issue by kyriej** [dueeeke/dkplayer#82]

**Comment by dueeeke** [comment]
在setplayerstate中隐藏就好
https://github.com/dueeeke/dkplayer/blob/master/dkplayer-ui/src/main/java/com/dueeeke/videocontroller/StandardVideoController.java#L158

**Comment by kyriej** [comment]
已解决，tks
