### ISSUE TITLE
切换视频时从头开始

### ISSUE THREAD

**Issue by peiniwan** [dueeeke/dkplayer#84]

**Comment by peiniwan** [comment]
已经解决了，是切换视频清晰度时会从头播放

**Comment by pz-bottle** [comment]
> 已经解决了，是切换视频清晰度时会从头播放

你用的是那个播放内核？我用了exo播放内核做切换清晰度也是从头开始播放的，可能是不支持吧，我提了是不是只有ijk才支持清晰度的，但是大佬们都没有回我
