### ISSUE TITLE
Seekbar在list fragment viewpager里的手势冲突

### ISSUE THREAD

**Issue by MIkeeJY** [dueeeke/dkplayer#9]
播放视频之后滑动seekbar 会触发viewpager的滑动，如何解决？

**Comment by dueeeke** [comment]
已解决，切到dev分支查看

**Comment by MIkeeJY** [comment]
public class DisallowInterceptSeekBar extends SeekBar {
    public DisallowInterceptSeekBar(Context var1) {
        super(var1);
    }

    public DisallowInterceptSeekBar(Context var1, AttributeSet var2) {
        super(var1, var2);
    }

    public DisallowInterceptSeekBar(Context var1, AttributeSet var2, int var3) {
        super(var1, var2, var3);
    }

    public boolean onTouchEvent(MotionEvent var1) {
        x.b("touch_test", "SeekBar onTouchEvent");
        ViewParent var2 = this.getParent();
        if(var2 != null) {
            var2.requestDisallowInterceptTouchEvent(true);
        }

        return super.onTouchEvent(var1);
    }
}

**Comment by dueeeke** [comment]
@MIkeeJY 不用那么复杂，最新版本已经解决
