### ISSUE TITLE
全頻縮回

### ISSUE THREAD

**Issue by PascalTang** [dueeeke/dkplayer#94]
全螢幕要變回原本時
若不是按icon
而是按onBackpress的按鈕
畫面會跑版

**Comment by dueeeke** [comment]
@Override
    public void onBackPressed() {
        if (!ijkVideoView.onBackPressed()) {
            super.onBackPressed();
        }
    }

**Comment by PascalTang** [comment]
ijkVideoView.onBackPressed()
有問題 不是沒有Override
